"use client";

import React, { useMemo, useRef, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Sparkles, Wand2, BrainCircuit, Map, CalendarClock, Download, RefreshCw,
  CheckCircle2, XCircle, ChevronRight, Target, TrendingUp, AlertTriangle, FileText, Send,
} from "lucide-react";
import { QUIZ_BANK, QuizQ, MASTERY_TOPICS } from "@/lib/data";
import { useApp } from "@/lib/store";
import { Badge, Btn, Card, Field, Select, Progress, SectionTitle } from "./ui";
import { HBar, Donut } from "./charts";

const GEN_STEPS = ["Analyzing curriculum standards…", "Sampling topic blueprint…", "Drafting distractors & explanations…", "Calibrating difficulty curve…", "Quality-checking items…"];

function useGeneration() {
  const [phase, setPhase] = useState<number>(-1); // -1 idle, 0..n generating
  const run = (onDone: () => void) => {
    setPhase(0);
    let i = 0;
    const t = setInterval(() => {
      i++;
      if (i >= GEN_STEPS.length) {
        clearInterval(t);
        setPhase(-1);
        onDone();
      } else setPhase(i);
    }, 620);
  };
  return { phase, run };
}

function downloadFile(name: string, content: string, type = "text/markdown") {
  const url = URL.createObjectURL(new Blob([content], { type }));
  const a = document.createElement("a");
  a.href = url; a.download = name; a.click();
  setTimeout(() => URL.revokeObjectURL(url), 2000);
}

// ─── AI Quiz Generator ──────────────────────────────────────
export function QuizGenerator({ role }: { role: "student" | "instructor" }) {
  const { toast } = useApp();
  const topics = Object.keys(QUIZ_BANK);
  const [topic, setTopic] = useState(topics[0]);
  const [difficulty, setDifficulty] = useState("Mixed");
  const [count, setCount] = useState(5);
  const [quiz, setQuiz] = useState<QuizQ[] | null>(null);
  const [mode, setMode] = useState<"edit" | "take">("edit");
  const [answers, setAnswers] = useState<Record<number, number>>({});
  const [revealed, setRevealed] = useState(false);
  const gen = useGeneration();
  const used = useRef(317); // of 1000 monthly

  const generate = () => {
    gen.run(() => {
      const bank = [...QUIZ_BANK[topic]];
      // deterministic-ish shuffle
      bank.sort(() => 0.5 - Math.random());
      setQuiz(bank.slice(0, Math.min(count, bank.length)));
      setAnswers({}); setRevealed(false); setMode(role === "student" ? "take" : "edit");
      used.current += 1;
      toast("Quiz generated", `${Math.min(count, bank.length)} export-ready items drafted for ${topic}.`, "ok");
    });
  };

  const score = quiz ? quiz.reduce((acc, q, i) => acc + (answers[i] === q.answer ? 1 : 0), 0) : 0;
  const exportQuiz = () => {
    if (!quiz) return;
    const md = `# ${topic} — ${difficulty} Quiz\nGenerated by EduNova AI · ${new Date().toLocaleDateString()}\n\n` +
      quiz.map((q, i) => `**Q${i + 1}. ${q.q}**\n` + q.options.map((o, j) => `- ${String.fromCharCode(65 + j)}) ${o}`).join("\n") + `\n> **Answer:** ${String.fromCharCode(65 + q.answer)} — ${q.expl}\n`).join("\n");
    downloadFile(`${topic.replace(/[^a-z]+/gi, "_")}_quiz.md`, md);
  };

  return (
    <div className="grid lg:grid-cols-[340px_1fr] gap-5">
      <Card className="p-5 h-fit lg:sticky lg:top-24">
        <SectionTitle icon={<Wand2 size={16} />} title="AI Quiz Generator" sub="Up to 1,000 AI-generated quizzes / month" />
        <div className="space-y-4">
          <Field label="Topic / unit">
            <Select value={topic} onChange={(e) => setTopic(e.target.value)}>{topics.map((t) => <option key={t}>{t}</option>)}</Select>
          </Field>
          <Field label="Difficulty">
            <Select value={difficulty} onChange={(e) => setDifficulty(e.target.value)}>
              {["Foundational", "Mixed", "Advanced", "Exam-grade"].map((d) => <option key={d}>{d}</option>)}
            </Select>
          </Field>
          <Field label={`Questions · ${count}`}>
            <input type="range" min={3} max={6} value={count} onChange={(e) => setCount(Number(e.target.value))} className="w-full accent-indigo-500" />
          </Field>
          <Btn className="w-full" icon={<Sparkles size={15} />} onClick={generate} disabled={gen.phase >= 0}>
            {gen.phase >= 0 ? "Generating…" : "Generate quiz"}
          </Btn>
          <div>
            <div className="flex justify-between text-[11px] text-slate-500 mb-1.5"><span>Monthly AI quota</span><span>{used.current} / 1,000</span></div>
            <Progress value={(used.current / 1000) * 100} color="#a78bfa" height={6} />
          </div>
          <div className="rounded-xl bg-violet-500/8 border border-violet-400/20 p-3 text-[11px] text-violet-200/80 leading-relaxed">
            Drafts include answer keys, distractor rationale and explanations — export-ready for print, LMS import or Google Forms.
          </div>
        </div>
      </Card>

      <div>
        <AnimatePresence mode="wait">
          {gen.phase >= 0 && (
            <motion.div key="gen" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="glass rounded-2xl p-10 flex flex-col items-center gap-5 min-h-[380px] justify-center">
              <motion.div animate={{ rotate: 360 }} transition={{ duration: 2.4, repeat: Infinity, ease: "linear" }}
                className="w-16 h-16 rounded-2xl bg-gradient-to-br from-violet-500 to-indigo-500 grid place-items-center shadow-xl shadow-violet-500/30">
                <BrainCircuit size={28} className="text-white" />
              </motion.div>
              <div className="space-y-2 w-full max-w-xs">
                {GEN_STEPS.slice(0, gen.phase + 1).map((s, i) => (
                  <motion.p key={s} initial={{ opacity: 0, x: -8 }} animate={{ opacity: i === gen.phase ? 1 : 0.45, x: 0 }} className="text-xs text-slate-300 flex items-center gap-2">
                    {i < gen.phase ? <CheckCircle2 size={12} className="text-emerald-400" /> : <span className="w-3 h-3 rounded-full border-2 border-violet-400 border-t-transparent animate-spin" />} {s}
                  </motion.p>
                ))}
              </div>
            </motion.div>
          )}
          {!quiz && gen.phase < 0 && (
            <motion.div key="empty" initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="glass rounded-2xl border-dashed p-12 min-h-[380px] grid place-items-center text-center">
              <div>
                <Wand2 size={34} className="mx-auto text-violet-400/60 mb-4" />
                <p className="font-display text-white font-semibold">Your generated quiz will appear here</p>
                <p className="text-xs text-slate-500 mt-2 max-w-[300px] mx-auto">Pick a topic and difficulty — the engine drafts auto-graded items with keys and explanations in seconds.</p>
              </div>
            </motion.div>
          )}
          {quiz && gen.phase < 0 && (
            <motion.div key="quiz" initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} className="space-y-4">
              <div className="flex flex-wrap items-center justify-between gap-3">
                <div className="flex items-center gap-2.5">
                  <Badge tone="violet" dot>{topic}</Badge>
                  <Badge tone="slate">{difficulty}</Badge>
                  <Badge tone="cyan">{quiz.length} items</Badge>
                </div>
                <div className="flex gap-2">
                  {role === "student" && quiz && (
                    <Btn size="sm" variant={mode === "take" ? "primary" : "ghost"} onClick={() => { setMode("take"); setRevealed(false); }}>Take quiz</Btn>
                  )}
                  <Btn size="sm" variant="outline" icon={<Download size={13} />} onClick={exportQuiz}>Export draft</Btn>
                  <Btn size="sm" variant="ghost" icon={<RefreshCw size={13} />} onClick={generate}>Regenerate</Btn>
                  {role === "instructor" && <Btn size="sm" icon={<Send size={13} />} onClick={() => toast("Quiz assigned", "Published to Grade 10-A with due date Friday.")}>Assign to class</Btn>}
                </div>
              </div>
              {revealed && (
                <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} className="glass rounded-2xl p-5 flex items-center gap-5">
                  <Donut value={(score / quiz.length) * 100} size={86} color={score / quiz.length >= 0.8 ? "#34d399" : score / quiz.length >= 0.6 ? "#fbbf24" : "#fb7185"} label={`${score}/${quiz.length}`} />
                  <div>
                    <p className="font-display font-semibold text-white">{score / quiz.length >= 0.8 ? "Excellent — mastery confirmed" : score / quiz.length >= 0.6 ? "Solid — a little polish needed" : "Review recommended"}</p>
                    <p className="text-xs text-slate-400 mt-1">Explanations are unlocked under each question.</p>
                  </div>
                </motion.div>
              )}
              {quiz.map((q, i) => {
                const chosen = answers[i];
                return (
                  <motion.div key={i} initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.06 }}>
                    <Card className="p-5">
                      <p className="text-sm font-semibold text-white"><span className="text-violet-300 font-display mr-2">Q{i + 1}.</span>{q.q}</p>
                      <div className="grid sm:grid-cols-2 gap-2 mt-3.5">
                        {q.options.map((o, j) => {
                          const isAnswer = j === q.answer, isChosen = chosen === j;
                          let cls = "border-white/10 hover:border-violet-400/40 text-slate-300";
                          if (mode === "take" && isChosen && !revealed) cls = "border-violet-400/70 bg-violet-500/12 text-white";
                          if (mode === "edit" && isAnswer) cls = "border-emerald-400/40 bg-emerald-500/8 text-emerald-200";
                          if (revealed && isAnswer) cls = "border-emerald-400/60 bg-emerald-500/12 text-emerald-200";
                          if (revealed && isChosen && !isAnswer) cls = "border-rose-400/60 bg-rose-500/12 text-rose-200";
                          return (
                            <button key={j} disabled={revealed || mode === "edit"} onClick={() => setAnswers((a) => ({ ...a, [i]: j }))}
                              className={`text-left text-xs px-3.5 py-2.5 rounded-xl border transition-all flex items-center gap-2.5 ${cls}`}>
                              <span className="w-5 h-5 rounded-md grid place-items-center text-[10px] font-bold bg-white/8 shrink-0">{String.fromCharCode(65 + j)}</span>
                              <span className="flex-1">{o}</span>
                              {revealed && isAnswer && <CheckCircle2 size={14} className="text-emerald-400 shrink-0" />}
                              {revealed && isChosen && !isAnswer && <XCircle size={14} className="text-rose-400 shrink-0" />}
                              {mode === "edit" && isAnswer && <Badge tone="green">key</Badge>}
                            </button>
                          );
                        })}
                      </div>
                      {(mode === "edit" || revealed) && (
                        <motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="text-[11px] text-slate-400 mt-3 pl-1 border-l-2 border-violet-400/30 ml-1" style={{ paddingLeft: 10 }}>
                          {q.expl}
                        </motion.p>
                      )}
                    </Card>
                  </motion.div>
                );
              })}
              {mode === "take" && !revealed && (
                <Btn className="w-full" size="lg" disabled={Object.keys(answers).length < quiz.length} onClick={() => setRevealed(true)} icon={<CheckCircle2 size={16} />}>
                  Submit answers · {Object.keys(answers).length}/{quiz.length} answered
                </Btn>
              )}
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}

// ─── AI Reports ─────────────────────────────────────────────
export function AIReportPanel({ who }: { who: "student" | "teacher" }) {
  const gen = useGeneration();
  const [report, setReport] = useState(false);
  const insights = who === "student"
    ? [
        { icon: <TrendingUp size={15} />, tone: "#34d399", title: "Strong upward trend in Mathematics", body: "Scores improved +14 pts over 5 assessments. Transformation fluency is now a strength — leverage it for logarithms, where the same composition thinking applies." },
        { icon: <AlertTriangle size={15} />, tone: "#fbbf24", title: "Logarithms need targeted practice", body: "47% topic mastery vs 78% class median. Recommend 3 × 20-minute micro-drill blocks weekly plus the interactive 'Log laws workshop' (lesson l8)." },
        { icon: <Target size={15} />, tone: "#22d3ee", title: "Capstone readiness: 86%", body: "8 of 9 Algebra lessons complete. Finish 'Capstone briefing' and submit the modeling proposal by Friday to stay on the distinction track." },
        { icon: <BrainCircuit size={15} />, tone: "#a78bfa", title: "Study-pattern insight", body: "Peak quiz performance follows same-day review (avg 91%) vs next-day review (74%). Suggest 15-minute evening recall sessions." },
      ]
    : [
        { icon: <TrendingUp size={15} />, tone: "#34d399", title: "Class mastery up 9% this term", body: "Grade 10-A moved from 71% → 80% average topic mastery. The pair-teaching workshop on inverse functions correlated with the largest single gain (+11%)." },
        { icon: <AlertTriangle size={15} />, tone: "#fbbf24", title: "2 students trending at-risk", body: "Noah B. (52% midterm, 2 missing submissions) and Liam O. (61%) need intervention. Suggested: guardian conference + scaffolded problem sets." },
        { icon: <Target size={15} />, tone: "#22d3ee", title: "Optimal pacing detected", body: "Quizzes released within 48h of a lesson earn 12% higher scores. Current pacing calendar already aligns — keep the Tuesday/Friday cadence." },
        { icon: <BrainCircuit size={15} />, tone: "#a78bfa", title: "Workload sustainability", body: "Grading turnaround averaged 1.8 days (target ≤ 3). Projected peak load in exam week: 38 scripts/day — consider scheduling TA support for days 2–4." },
      ];
  return (
    <Card className="p-5">
      <div className="flex flex-wrap items-center justify-between gap-3 mb-5">
        <SectionTitle icon={<FileText size={16} />} title={who === "student" ? "AI Progress Report — Aarav" : "AI Teaching Performance Report"} sub="Actionable insight summary · generated on demand" />
        <Btn size="sm" icon={<Sparkles size={14} />} onClick={() => gen.run(() => setReport(true))} disabled={gen.phase >= 0}>{report ? "Refresh report" : "Generate report"}</Btn>
      </div>
      <AnimatePresence mode="wait">
        {gen.phase >= 0 && (
          <motion.div key="loading" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="py-10 flex flex-col items-center gap-3">
            <motion.div animate={{ rotate: 360 }} transition={{ duration: 2, repeat: Infinity, ease: "linear" }}><BrainCircuit size={30} className="text-violet-400" /></motion.div>
            <p className="text-xs text-slate-400">{GEN_STEPS[gen.phase]}</p>
          </motion.div>
        )}
        {!report && gen.phase < 0 && (
          <motion.p key="empty" initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="text-xs text-slate-500 text-center py-10">
            Generate a smart report — synthesized from attendance, grade book, engagement and diary signals.
          </motion.p>
        )}
        {report && gen.phase < 0 && (
          <motion.div key="rpt" className="grid md:grid-cols-2 gap-3.5">
            {insights.map((ins, i) => (
              <motion.div key={ins.title} initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.1 }} className="glass-soft rounded-xl p-4">
                <div className="flex items-center gap-2.5 mb-2">
                  <span className="w-8 h-8 rounded-lg grid place-items-center" style={{ background: `${ins.tone}1c`, color: ins.tone }}>{ins.icon}</span>
                  <p className="text-[13px] font-semibold text-white leading-snug">{ins.title}</p>
                </div>
                <p className="text-xs text-slate-400 leading-relaxed">{ins.body}</p>
              </motion.div>
            ))}
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.45 }} className="md:col-span-2 flex justify-end">
              <Btn size="sm" variant="outline" icon={<Download size={13} />} onClick={() => downloadFile("edunova_ai_report.md", `# EduNova AI Report\nGenerated ${new Date().toLocaleString()}\n\n` + insights.map((i) => `## ${i.title}\n${i.body}\n`).join("\n"))}>
                Export report (.md)
              </Btn>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </Card>
  );
}

// ─── Personalized syllabus ──────────────────────────────────
export function PersonalizedSyllabus() {
  const gen = useGeneration();
  const [ready, setReady] = useState(false);
  const plan = [
    { week: "Week 1", focus: "Logarithm laws — from first principles", why: "Lowest mastery (47%) and a gateway to the capstone", tag: "Priority" },
    { week: "Week 2", focus: "Exponential models + half-life drills", why: "Adjacent weakness (58%); pairs with log laws", tag: "Priority" },
    { week: "Week 3", focus: "Rational expressions consolidation", why: "64% → target 80% with mixed problem sets", tag: "Strengthen" },
    { week: "Week 4", focus: "Function modeling studio (capstone lane)", why: "Converts strengths into the 200-point capstone", tag: "Capstone" },
    { week: "Week 5", focus: "Timed mixed review + error-log review", why: "Spaced repetition of all flagged topics", tag: "Mastery" },
  ];
  return (
    <div className="grid lg:grid-cols-[360px_1fr] gap-5">
      <Card className="p-5 h-fit">
        <SectionTitle icon={<Map size={16} />} title="Mastery Map" sub="Per-topic mastery — AI audited" />
        <div className="space-y-3.5">
          {MASTERY_TOPICS.map((t, i) => (
            <HBar key={t.topic} label={t.topic} pct={t.pct} color={t.pct >= 75 ? "#34d399" : t.pct >= 55 ? "#fbbf24" : "#fb7185"} />
          ))}
        </div>
        <div className="mt-5 rounded-xl bg-rose-500/8 border border-rose-400/20 p-3.5">
          <p className="text-[11px] font-semibold text-rose-300 flex items-center gap-1.5"><AlertTriangle size={12} /> Detected weakness cluster</p>
          <p className="text-[11px] text-slate-400 mt-1 leading-relaxed">Logarithms & Exponentials — blocking the modeling capstone worth 200 pts.</p>
        </div>
        <Btn className="w-full mt-4" icon={<Sparkles size={14} />} disabled={gen.phase >= 0} onClick={() => gen.run(() => setReady(true))}>
          {ready ? "Re-personalize path" : "Generate personalized syllabus"}
        </Btn>
      </Card>
      <Card className="p-5 min-h-[420px]">
        <SectionTitle icon={<Target size={16} />} title="Adaptive Improvement Path" sub="Goal: exam-ready in 5 weeks · calibrated to your pace" />
        {gen.phase >= 0 && (
          <div className="py-14 flex flex-col items-center gap-3">
            <motion.div animate={{ rotate: 360 }} transition={{ duration: 2, repeat: Infinity, ease: "linear" }}><BrainCircuit size={30} className="text-violet-400" /></motion.div>
            <p className="text-xs text-slate-400">{GEN_STEPS[gen.phase]}</p>
          </div>
        )}
        {!ready && gen.phase < 0 && (
          <p className="text-xs text-slate-500 text-center py-14">The engine will reorder your syllabus around weaknesses and goals.</p>
        )}
        {ready && gen.phase < 0 && (
          <div className="relative pl-6">
            <span className="absolute left-[9px] top-2 bottom-2 w-[2px] bg-gradient-to-b from-violet-500 via-cyan-400 to-emerald-400 rounded" />
            <div className="space-y-4">
              {plan.map((p, i) => (
                <motion.div key={p.week} initial={{ opacity: 0, x: 18 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: i * 0.1 }} className="relative">
                  <span className="absolute -left-6 top-1.5 w-[14px] h-[14px] rounded-full bg-[#06090f] border-2 border-violet-400" />
                  <div className="glass-soft rounded-xl p-4">
                    <div className="flex items-center justify-between gap-2 flex-wrap">
                      <p className="text-sm font-semibold text-white">{p.week} · {p.focus}</p>
                      <Badge tone={p.tag === "Priority" ? "red" : p.tag === "Capstone" ? "violet" : "cyan"}>{p.tag}</Badge>
                    </div>
                    <p className="text-xs text-slate-400 mt-1.5">{p.why}</p>
                  </div>
                </motion.div>
              ))}
            </div>
          </div>
        )}
      </Card>
    </div>
  );
}

// ─── Test session planner ───────────────────────────────────
export function TestPlanner() {
  const gen = useGeneration();
  const [ready, setReady] = useState(false);
  const weeks = useMemo(() => {
    const subjects = ["Algebra", "Physics", "English", "CompSci", "History", "Chemistry"];
    const phases = ["Foundation", "Foundation", "Foundation", "Intermediate", "Intermediate", "Intermediate", "Intermediate", "Advanced", "Advanced", "Advanced", "Mastery Mock", "Mastery Mock", "Mastery Mock", "Review Sprint", "Review Sprint", "Final Rehearsal"];
    return phases.map((phase, i) => ({
      week: i + 1, phase,
      subject: subjects[i % subjects.length],
      focus: ["Core concepts check", "Timed section drill", "Error-log deep dive", "Full paper simulation"][i % 4],
      mins: 45 + (i % 3) * 15,
    }));
  }, []);
  const exportICS = () => {
    const now = new Date();
    const evs = weeks.map((w) => {
      const d = new Date(now); d.setDate(d.getDate() + w.week * 7);
      const dt = `${d.getFullYear()}${String(d.getMonth() + 1).padStart(2, "0")}${String(d.getDate()).padStart(2, "0")}T160000`;
      return `BEGIN:VEVENT\nUID:edunova-w${w.week}@edunova\nDTSTART:${dt}\nDURATION:PT${w.mins}M\nSUMMARY:[EduNova] ${w.phase} — ${w.subject} (${w.focus})\nEND:VEVENT`;
    }).join("\n");
    downloadFile("edunova_test_plan.ics", `BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//EduNova OS//EN\n${evs}\nEND:VCALENDAR`, "text/calendar");
  };
  const phaseColor: Record<string, string> = { Foundation: "#22d3ee", Intermediate: "#a78bfa", Advanced: "#f59e0b", "Mastery Mock": "#fb7185", "Review Sprint": "#34d399", "Final Rehearsal": "#fbbf24" };
  return (
    <Card className="p-5">
      <div className="flex flex-wrap items-center justify-between gap-3 mb-5">
        <SectionTitle icon={<CalendarClock size={16} />} title="AI Test Session Planner — Final 4 Months" sub="16 weekly sessions · scheduled by weakness & goal weighting" />
        <div className="flex gap-2">
          <Btn size="sm" icon={<Sparkles size={14} />} disabled={gen.phase >= 0} onClick={() => gen.run(() => setReady(true))}>{ready ? "Re-plan season" : "Generate 4-month plan"}</Btn>
          {ready && <Btn size="sm" variant="outline" icon={<Download size={13} />} onClick={exportICS}>Export .ics</Btn>}
        </div>
      </div>
      {gen.phase >= 0 && (
        <div className="py-14 flex flex-col items-center gap-3">
          <motion.div animate={{ rotate: 360 }} transition={{ duration: 2, repeat: Infinity, ease: "linear" }}><BrainCircuit size={30} className="text-violet-400" /></motion.div>
          <p className="text-xs text-slate-400">{GEN_STEPS[gen.phase]}</p>
        </div>
      )}
      {!ready && gen.phase < 0 && <p className="text-xs text-slate-500 text-center py-14">The planner distributes sessions across your final 3–4 months — heavier on weak topics, tapering into mock exams.</p>}
      {ready && gen.phase < 0 && (
        <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3">
          {weeks.map((w, i) => (
            <motion.div key={w.week} initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.035 }} className="glass-soft rounded-xl p-3.5 relative overflow-hidden group hover:border-white/20 transition">
              <span className="absolute top-0 left-0 right-0 h-[3px]" style={{ background: phaseColor[w.phase] }} />
              <div className="flex items-center justify-between">
                <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">Week {w.week}</span>
                <span className="text-[10px] font-semibold" style={{ color: phaseColor[w.phase] }}>{w.phase}</span>
              </div>
              <p className="text-[13px] font-semibold text-white mt-1.5">{w.subject}</p>
              <p className="text-[11px] text-slate-400 mt-0.5">{w.focus}</p>
              <p className="text-[10px] text-slate-500 mt-2 flex items-center gap-1"><CalendarClock size={10} /> {w.mins} min · auto-scheduled</p>
            </motion.div>
          ))}
        </div>
      )}
    </Card>
  );
}
